### ISSUE TITLE
Project Charter

### ISSUE THREAD

**Issue by kishu** [FrontEndDev-Group/feconf2018#1]
## Objective
* FECONF가 국내 프론트엔드 컨퍼런스로써의 대표성을 가지자

## Scope
* Homepage w/ registration system
* Call For Paper
* Manage registration
* Booking / Manage conference hall w/ natworking, (finger food)
* Publishing Recoding, Presentation
* Recruit Speaker
* Recruit Sponsor
* Recruit Staff
* Goods

## Organize / R&R
* Chair man: 주우영
* Place : 김홍기

## Milestones
* Date : 2018-10-13 (Sat, 둘째주)
* Budget : (2017년 기준) -> 구글닥스 확인
* Scale : 300명 (2 Track, 12 Sessions)
* Place : 후보

## Summary Budget
* 900만원 + a

## Success Criteria
* 300명이 무사히 왔다.
* 적자나지 않았으면 좋겠다.
* 언론 기사 났으면 좋겠다.
* 소셜에 많이 언급되면 좋겠다. (후기)
* 오거나이저들 잘해라..........

## High Level Risks
* 장소
* 발표자
* 스폰서
* 오거나이저의 정신건강

## Meetings
* Kick Off: 2018.07.04(wed) 19:00
* Where: [D2 Startup Factory](http://www.d2startup.com/) [[Map]](https://map.naver.com/?pinId=36797269&dlevel=12&enc=b64&pinType=site&y=d8a4ee8308e25df6f8548a85756f5c47&x=ffbd4e28919362159a238ad07e14ecb1)
* To reserve a meeting room, click [here](https://booking.naver.com/booking/10/bizes/117478) / Meeting room **B** recommendation
* The first few weeks meet on Wednesdays every two weeks.
* Meet on Wednesdays when the D-day is near.

**Comment by techhtml** [comment]
Kick off #2 
2nd meeting #14
