### ISSUE TITLE
스폰서 모집

### ISSUE THREAD

**Issue by kishu** [FrontEndDev-Group/feconf2018#12]
* 레진 - 메일발송
* 토스 - 구두협의
* 네이버 - 구두협의
* 카카오 - 지인찬스 이용예정

**Comment by kishu** [comment]
은혜로우신 토스

**Comment by techhtml** [comment]
초대권은 10장 / 5장 / 3장 어떠세요.

**Comment by kishu** [comment]
2017 후원사 모집 템플릿
https://docs.google.com/document/d/1EdL9rkZ5yAX91O3_8smk5nJjGewsrYAXIM4U57V8XtQ/edit

**Comment by kishu** [comment]
![image](https://user-images.githubusercontent.com/13197080/43571151-2dbc62ac-9677-11e8-99e6-e3eab227653f.png)

**Comment by kishu** [comment]
move to #29
