### ISSUE TITLE
브랜딩

### ISSUE THREAD

**Issue by techhtml** [FrontEndDev-Group/feconf2018#13]
FEConf 앞으로 어떻게 운영해나갈 지에 대한 전반적인 브랜딩을 진행하면 좋을 거 같습니다.

**Comment by kishu** [comment]
좀만 더 구체적으로 어떤걸 어떻게 브랜딩 하면 좋을까여?
이 주제가 어떤 결과가 나오면 좋을지 알려주세여...

**Comment by techhtml** [comment]
1. FEConf의 컨셉

FEConf가 매년마다 Conference를 주최해나가면서,
Conference의 방향성을 다시 잡고 있지만, FEConf 자체만의 컨셉은 무엇인가에 대해서 이야기를 안나눈 거 같아요.

그게 지난 번에 이야기한 '누군가의 FE 경험을 공유한다' 가 되었던 뭐가 되었던 그런 류의 가닥이 있어야할 거 같습니다.

2. 향후 운영방식

지금은 지인 Base로 Speaker나 Staff를 모집하고 있는데요.

이것도 지인 Base가 아니라 좀 더 확장해서 이벤트를 할 때마다 팀을 꾸려서 운영하는 등의 조치가 필요해보입니다.
(저희가 평생 FEConf를 할 게 아니라면) 지속 가능한 컨퍼런스가 되려면 아무래도 Organizer가 고인물이 되면 안될 거 같아요.

3. FEConf와 프론트엔드개발그룹

FEConf가 공식적으로는 프론트엔드개발그룹의 컨퍼런스 같은 형태를 취하고있고,
프론트엔드개발그룹의 운영진들이 FEConf에 오거나이징 하고 있는데,
이 두개의 관계가 명확해지고, 프론트엔드개발그룹을 어떻게 운영해나갈 지에 대해서도 정해져야,
향후 커뮤니티의 관계성이 명확해 질 거 같습니다.

**Comment by techhtml** [comment]
### 슬로건 or 컨셉
주우영 : Future (미래)
서정명 : Trend (트렌드)

문주영 : Experience (경험)
은 : Grow up (성장)
태훈 : Enjoy (즐거움)
재엽 : Everywhere (어디서나)
훈민 : Network
뀨 : Share (공유)

*경험을 공유하는 즐거움을 통해 성장하고 미래를 준비한다*

**Comment by kishu** [comment]
더 이상 의견 없고
컨센선스 맞춰진듯 함. close
