### ISSUE TITLE
단체 명의 통장 개설

### ISSUE THREAD

**Issue by kishu** [FrontEndDev-Group/feconf2018#31]
* 고유번호증 원본
* 단체명의 직인
* 대표자 신분증

체크카드 꼭 함께 발급하자요.
이거 누가 개설해야 하나? 회계 담당? 대표자?

refer
#8 비영리 단체 설립
#23 회계 및 정산

**Comment by jungmyung** [comment]
낼 은행가서 한번 시도해 보겠습니다~
대표자 신분증 없어서 안되면 @kishu 고유번호증 갖고 직접 가셔야 할듯요.

**Comment by kishu** [comment]
이거 제가 가서 해야 할듯요.

**Comment by kishu** [comment]
통장 개설 완료

![image from ios](https://user-images.githubusercontent.com/13197080/44637750-f0608200-a9ed-11e8-838b-c11cb3d1fceb.jpg)
