### ISSUE TITLE
Call for Speakers

### ISSUE THREAD

**Issue by techhtml** [FrontEndDev-Group/feconf2018#7]
**주제 아이데이션**
전제조건 : Service화 했던 경험담
회사를 되도록 넓게 하면 좋겠다.
**내부용입니다**

* Bundle
* MonoRepo
* TypeScript
* Performance
* Enterprise
* Design Pattern
* HTML & CSS
  * CSS Animation
  * CSS Layout (Grid)
* WebKit
* WebGL
* PWA (Progressive Web Apps)
* WASM
* AMP Project
* Web Framework
* ECMA deep dive
* 중앙일보 판문점 개발자 섭외 (@hckrmoon ) 
  * http://news.joins.com/DigitalSpecial/290
  * https://www.facebook.com/profile.php?id=100001269794643&fref=gs&dti=400867776724630&hc_location=group_dialog
* strapi
* Game UI
* test 관련 (Unit Test, E2E Test)
* Frontend 개발자 머신러닝 첫걸음 (@kishu)
* 주니어에서 시니어가 될 때...

**Comment by CoderK** [comment]
이 발표자료 저는 재밌게 봤는데, 발표 후보자로 올려서 검토해봐도 좋을 듯 해요.
(발표자료만 본거라... 어떤 분인지는 모르겠네요)

https://www.slideshare.net/ssuser44df45/why-typescript-with-clean-architecture-82371194

**Comment by techhtml** [comment]
내일까지 작업해서 @UYEONG 님이 공유
이번 주 내로 업로드

**Comment by kishu** [comment]
![image](https://user-images.githubusercontent.com/13197080/43496462-7333ccda-9578-11e8-9a4d-1582db04b652.png)

**Comment by kishu** [comment]
![image](https://user-images.githubusercontent.com/13197080/43496473-8cb2925e-9578-11e8-9160-50afeeab4b66.png)
![image](https://user-images.githubusercontent.com/13197080/43496478-95295788-9578-11e8-8b43-4d03e8c31d65.png)
![image](https://user-images.githubusercontent.com/13197080/43496488-9bb89b4a-9578-11e8-8695-d0633bac9a49.png)

**Comment by kishu** [comment]
자료 제공 동의서도 CFS로 받자

**Comment by CoderK** [comment]
이거 재엽 님 피드백 반영해서 확정하시죠!!!

2018년 8월 1일 (수) 오후 8:22, Jbee <notifications@github.com>님이 작성:

**Comment by JaeYeopHan** [comment]
https://docs.google.com/forms/d/1Z0GXx7W4l01R2ebcNdfFWNezUhPPqnxFNfiOHSaCcZY/edit

### 8/8 논의해야할 내용

#### 질문

- 소속 / GitHub 등의 기타 정보는 받지 않는가? 
  - 받을 경우, 밝히고 싶지 않을 경우가 있을 수 있다. (필수가 아닌 질문으로 등록?)
  - 받지 않을 경우, 추후 공식 웹페이지를 통해 연사를 소개할 때 한 번 더 요청을 해야하는 번거로움이 존재한다.

- 핸드폰 번호?
  - 개인적으로는 발표 당일 원활한 커뮤니케이션을 위해 필요하다고 생각.

#### 네 가지의 '언제'에 대한 협의가 필요

- 본 모집은 **언제**부터 **언제**까지 진행하며, 발표자 선정을 **언제** 진행하고 이를 **언제** 발표할 것인가
  - CFS 공개 날짜 : 
  - CFS 마감 날짜 : 
  - 발표자 선정 날짜 : 
  - 발표자 공개 날짜 : 

#### 추천인에 대한 선물

- 어떠한 선물을 줄 것인지?
- 그 이전에 이번에도 추천인 항목을 넣어 추천을 받을 것인지?

#### 발표 시간 명시

행사 타임테이블을 기반으로 하여 대략적인 발표 시간을 명시해줄 필요성이 있음.
-> 타임테이블이 나와야 함.

#### 검토 및 피드백

- 폼 전반적인 톤앤매너
- 맞춤법, 오탈자 등... (몇 번을 봐도 작성자는 잘 안 보임 ㅜㅜ)

**Comment by techhtml** [comment]
### 질문에 대한 답변
소속 / GitHub
=> 필수가 아닌 질문으로 등록

핸드폰번호
=> 받는 것이 커뮤니케이션 차 좋음

### 언제
CFS 공개 : 08.15
CFS 마감 : 08.29 (2weeks)
발표자 선정 : 08.31
발표자 공개 : 09.05 (홈페이지 제작에 따라 달라질듯?)

**Comment by kishu** [comment]
![image](https://user-images.githubusercontent.com/13197080/43748316-dfcb48d6-9a29-11e8-8748-aaa6b08b3e3b.png)

Enjoy Experience Everywhere

**Comment by kishu** [comment]
![image](https://user-images.githubusercontent.com/13197080/43748337-0181eb56-9a2a-11e8-988a-4440b299af37.png)

젤 위로 올리고

![image](https://user-images.githubusercontent.com/13197080/43748408-5a798278-9a2a-11e8-9e2d-3644018fba52.png)

이라 함

**Comment by JaeYeopHan** [comment]
@techhtml 님 의견에서 살짝 조율해봤는데요,

- CFS 공개 날짜 : 08.13 월
- CFS 마감 날짜 : 08.28 화
- 발표자 선정 날짜 : 08.29 수 (회의 때 함께 선정)
- 발표자 공개 날짜 : 홈페이지 제작 후 공개 전날 메일로 공개

어떠신가요?

**Comment by kishu** [comment]
전체적으로 간결하게 해 보자 
훈민이 다음어 주삼

**Comment by CoderK** [comment]
@JaeYeopHan 다듬었어요. 확인하시고 마무리 부탁 드립니다~

**Comment by JaeYeopHan** [comment]
@CoderK 님, 확인했습니다! 훨씬 깔끔해졌습니다! 👍 

1. 어제 회의 때 논의되었던 날짜들 중 발표자에게 개별적으로 결과 메일을 보내는 날은 8월 31일로 하려고 합니다~ 연사분들께 공식 페이지 만들 때 필요한 정보들을 받으려면 페이지 공개 날짜보다 조금 빨라야 할 것 같아서요!
2. 추후 피드백 없으면 이대로 진행할 예정입니다~

https://docs.google.com/forms/d/e/1FAIpQLSdsBjiuL8UvF-wban8US82mWuYX1AH-4cxK1PY89QaIpNrcLg/viewform

**Comment by kishu** [comment]
good job
