### ISSUE TITLE
비영리 단체 설립

### ISSUE THREAD

**Issue by techhtml** [FrontEndDev-Group/feconf2018#8]

**Comment by jungmyung** [comment]
신청서류
 - 등록신청서
 - 회칙 또는 정관
 - 총 회의록
 - 회원명부
 - 참석자 서명부
 - 취임승낙서
 - 회장의 인감증명서와 인감도장
 - 사무실(임대차계약서 또는 무상사용의 경우 등기부등본)

**Comment by jungmyung** [comment]
오늘(7/18) 할 것!!
 - 대표자 정하기
 - 참석자 서명 받기

**Comment by techhtml** [comment]
단체명 : 프론트엔드개발그룹
대표자 : 김태훈 (인감 만들어 오세요)

**Comment by CoderK** [comment]
### 현 상황

@jungmyung 님이 회사에서 겸직 불가능하다고 안내 받아서 @kishu 님이 겸직 가능성 네이버에 문의 중.

**Comment by kishu** [comment]
good job 👍
